all:
	docker run -it --rm -v ${PWD}:/project launchiine-builder make

clean:
	docker run -it --rm -v ${PWD}:/project launchiine-builder make clean

# Add -i to actually do it?
clang: clean
	docker run -it --rm -v ${PWD}:/src wiiuenv/clang-format:13.0.0-2 -r ./src

init:
	docker build . -t launchiine-builder
